from .full_res import PSMNet as basic
from .stackhourglass import PSMNet as stackhourglass
from .stackhourglass_classif import PSMNet as stackhourglass_classif
from .stackhourglass_edge_aware import PSMNet as stackhourglass_edge_aware
from .stackhourglass_full import PSMNet as stackhourglass_full
from .stackhourglass_semantic import PSMNet as stackhourglass_semantic
from .stackhourglass_softmax_offset import PSMNet as stackhourglass_softmax_offset
from .stackhourglass_std import PSMNet as stackhourglass_std
from .stackhourglass_volume import PSMNet as stackhourglass_volume
from .stackhourglass_volume_large_off import PSMNet as stackhourglass_volume_large_off
from .stackhourglass_volume_multihead import PSMNet as stackhourglass_multihead
from .stackhourglass_volume_semantic import PSMNet as stackhourglass_volume_semantic
from .stackhourglass_win import PSMNet as stackhourglass_win
